
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Abhi
 */
public class Service_log extends javax.swing.JFrame {

    private Connection c;
    private static final String serverPath = "jdbc:mysql://localhost:3306/bike_service";
    private static final String username = "root";
    private static final String password = "root";

    /**
     * Creates new form Service_log
     */
    public Service_log() {
        initComponents();
        addedLabel.setVisible(false);
        allVehiclesEnrolledLabel.setVisible(false);
        allVehicleSummaryTable.setVisible(false);
        viewQuotationButton.setVisible(false);

        c = null;

        try {

            c = DriverManager.getConnection(serverPath, username, password);
            System.out.println("connected");

        } catch (Exception e) {
            System.err.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        serviceLogPanel = new javax.swing.JPanel();
        vehicleDeliveryTab = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        vmTable = new javax.swing.JTable();
        AddVehicleButton = new javax.swing.JButton();
        addedLabel = new javax.swing.JLabel();
        signOut = new javax.swing.JButton();
        deleteBikeModel = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        rsTable = new javax.swing.JTable();
        placeOrderButton = new javax.swing.JButton();
        orderPlacedLabel = new javax.swing.JLabel();
        signOut3 = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        qTable = new javax.swing.JTable();
        updateQuotationButton = new javax.swing.JButton();
        updateQuotationLabel = new javax.swing.JLabel();
        signOut2 = new javax.swing.JButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        searchVehicleText = new javax.swing.JTextField();
        searchVehicleButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        vehicleSummaryTable = new javax.swing.JTable();
        signOut1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        allVehicleSummaryTable = new javax.swing.JTable();
        allVehiclesEnrolledLabel = new javax.swing.JLabel();
        viewQuotationButton = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("Service Vendor Application"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        serviceLogPanel.setLayout(new java.awt.BorderLayout());

        vmTable.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        vmTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Bike Name", "Registration No", "Color", "Kilometers run"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        vmTable.setColumnSelectionAllowed(true);
        vmTable.setInheritsPopupMenu(true);
        jScrollPane1.setViewportView(vmTable);
        vmTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        AddVehicleButton.setText("Add Vehicle");
        AddVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVehicleButtonActionPerformed(evt);
            }
        });

        addedLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addedLabel.setForeground(new java.awt.Color(11, 191, 23));
        addedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addedLabel.setText("---");

        signOut.setBackground(new java.awt.Color(0, 0, 0));
        signOut.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        signOut.setForeground(new java.awt.Color(255, 255, 255));
        signOut.setText("Sign out");
        signOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutActionPerformed(evt);
            }
        });

        deleteBikeModel.setText("Remove Vehicle Record");
        deleteBikeModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBikeModelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1408, Short.MAX_VALUE)
            .addComponent(addedLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(AddVehicleButton)
                        .addGap(26, 26, 26)
                        .addComponent(deleteBikeModel))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(signOut)))
                .addContainerGap(965, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddVehicleButton)
                    .addComponent(deleteBikeModel))
                .addGap(18, 18, 18)
                .addComponent(addedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(signOut)
                .addContainerGap())
        );
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(AddVehicleButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(addedLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(signOut, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(deleteBikeModel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane2.addTab("Vehicle Model", jLayeredPane1);

        rsTable.setBorder(new javax.swing.border.MatteBorder(null));
        rsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Customer Name", "Bike Name", "Reg No", "Repair Category", "Customer Complaints"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(rsTable);

        placeOrderButton.setText("Place ORDER");
        placeOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderButtonActionPerformed(evt);
            }
        });

        orderPlacedLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        orderPlacedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderPlacedLabel.setText("---");

        signOut3.setBackground(new java.awt.Color(0, 0, 0));
        signOut3.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        signOut3.setForeground(new java.awt.Color(255, 255, 255));
        signOut3.setText("Sign out");
        signOut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOut3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1408, Short.MAX_VALUE)
            .addComponent(orderPlacedLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(placeOrderButton))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(signOut3)))
                .addContainerGap(1138, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(placeOrderButton)
                .addGap(36, 36, 36)
                .addComponent(orderPlacedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(signOut3)
                .addContainerGap())
        );
        jLayeredPane2.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(placeOrderButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(orderPlacedLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(signOut3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane2.addTab("Required Service", jLayeredPane2);

        qTable.setBorder(new javax.swing.border.MatteBorder(null));
        qTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Reg No", "cost", "for"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        qTable.setColumnSelectionAllowed(true);
        jScrollPane4.setViewportView(qTable);

        updateQuotationButton.setText("Update Quotation");
        updateQuotationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateQuotationButtonActionPerformed(evt);
            }
        });

        updateQuotationLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        updateQuotationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateQuotationLabel.setText("---");

        signOut2.setBackground(new java.awt.Color(0, 0, 0));
        signOut2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        signOut2.setForeground(new java.awt.Color(255, 255, 255));
        signOut2.setText("Sign out");
        signOut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOut2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1408, Short.MAX_VALUE)
            .addComponent(updateQuotationLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateQuotationButton)
                .addGap(147, 147, 147))
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(signOut2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateQuotationButton)
                .addGap(18, 18, 18)
                .addComponent(updateQuotationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(signOut2)
                .addContainerGap())
        );
        jLayeredPane3.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(updateQuotationButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(updateQuotationLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(signOut2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane2.addTab("Quotation", jLayeredPane3);

        vehicleDeliveryTab.addTab("Vehicle Intake", jTabbedPane2);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setText("Search Vehicle");

        searchVehicleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchVehicleTextActionPerformed(evt);
            }
        });
        searchVehicleText.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                searchVehicleTextPropertyChange(evt);
            }
        });

        searchVehicleButton.setText("Search");
        searchVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchVehicleButtonActionPerformed(evt);
            }
        });

        vehicleSummaryTable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        vehicleSummaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Bike Name", "Bike Color", "Vehicle No", "Kilometers Run", "Repair Category", "Customer Complaints", "Total Bill"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        vehicleSummaryTable.setEnabled(false);
        jScrollPane5.setViewportView(vehicleSummaryTable);

        signOut1.setBackground(new java.awt.Color(0, 0, 0));
        signOut1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        signOut1.setForeground(new java.awt.Color(255, 255, 255));
        signOut1.setText("Sign out");
        signOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOut1ActionPerformed(evt);
            }
        });

        allVehicleSummaryTable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        allVehicleSummaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Bike Name", "Bike Color", "Vehicle No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        allVehicleSummaryTable.setEnabled(false);
        jScrollPane6.setViewportView(allVehicleSummaryTable);

        allVehiclesEnrolledLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        allVehiclesEnrolledLabel.setText("Vehicle Record in <BikeService.h>");

        viewQuotationButton.setText("View Quotation");
        viewQuotationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewQuotationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(signOut1))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(allVehiclesEnrolledLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(searchVehicleText, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(searchVehicleButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(viewQuotationButton))
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(searchVehicleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchVehicleButton))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(viewQuotationButton)
                        .addGap(1, 1, 1)))
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(signOut1))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(allVehiclesEnrolledLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane4.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(searchVehicleText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(searchVehicleButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(signOut1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(allVehiclesEnrolledLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(viewQuotationButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        vehicleDeliveryTab.addTab("Vehicle Summary", jLayeredPane4);

        serviceLogPanel.add(vehicleDeliveryTab, java.awt.BorderLayout.CENTER);

        getContentPane().add(serviceLogPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutActionPerformed
        // TODO add your handling code here:
        login l = new login();
        setVisible(false);
        dispose();
        l.setVisible(true);
    }//GEN-LAST:event_signOutActionPerformed
    int i = 1;
    private void updateQuotationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateQuotationButtonActionPerformed
        // TODO add your handling code here:        
        DefaultTableModel model = (DefaultTableModel) qTable.getModel();

        try {
            String reg_no = model.getValueAt(0, 0).toString().toUpperCase();
            String costString = model.getValueAt(0, 1).toString();
            int cost = Integer.parseInt(costString);
            String cost_for = model.getValueAt(0, 2).toString();

            String query = "insert into bill_quotation(registration_no, cost, cost_for) values(?, ?, ?)";
            PreparedStatement preparedStmt = c.prepareStatement(query);

            preparedStmt.setString(1, reg_no);
            preparedStmt.setInt(2, cost);
            preparedStmt.setString(3, cost_for);

            preparedStmt.execute();
            updateQuotationLabel.setVisible(true);
            updateQuotationLabel.setText("Quotation updated count: " + (i++));

        } catch (Exception e) {
            System.out.println(e);
            updateQuotationLabel.setVisible(true);
            updateQuotationLabel.setText(e.toString());
        }

    }//GEN-LAST:event_updateQuotationButtonActionPerformed

    private void placeOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) rsTable.getModel();
        try {
            String customer_name = model.getValueAt(0, 0).toString();
            String bike_name = model.getValueAt(0, 1).toString();
            String reg_no = model.getValueAt(0, 2).toString().toUpperCase();
            String repair_category = model.getValueAt(0, 3).toString();
            String customer_complaints = model.getValueAt(0, 4).toString();

            String query = "insert into service(customer_name, bike_name, registration_no, repair_category, customer_complaints) values(?, ?, ?, ?, ?)";
            PreparedStatement preparedStmt = c.prepareStatement(query);

            preparedStmt.setString(1, customer_name);
            preparedStmt.setString(2, bike_name);
            preparedStmt.setString(3, reg_no);
            preparedStmt.setString(4, repair_category);
            preparedStmt.setString(5, customer_complaints);

            preparedStmt.execute();

            orderPlacedLabel.setVisible(true);
            orderPlacedLabel.setText("Order Placed");

        } catch (Exception e) {

            orderPlacedLabel.setVisible(true);
            orderPlacedLabel.setText(e.toString());
        }

    }//GEN-LAST:event_placeOrderButtonActionPerformed

    private void AddVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVehicleButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) vmTable.getModel();
        try {
            String bike_name = model.getValueAt(0, 0).toString();
            String reg_no = model.getValueAt(0, 1).toString().toUpperCase();
            String color = model.getValueAt(0, 2).toString();
            String kilometers = model.getValueAt(0, 3).toString();

            String query = "insert into bike_model(bike_name, registration_no, bike_color, kilometers_run) values(?, ?, ?, ?)";
            PreparedStatement preparedStmt = c.prepareStatement(query);

            preparedStmt.setString(1, bike_name);
            preparedStmt.setString(2, reg_no);
            preparedStmt.setString(3, color);
            preparedStmt.setString(4, kilometers);

            preparedStmt.execute();

            addedLabel.setVisible(true);
            addedLabel.setText("Vehicle Model added to the record successfully");

        } catch (Exception e) {
            addedLabel.setVisible(true);
            addedLabel.setText(e.toString());
        }

    }//GEN-LAST:event_AddVehicleButtonActionPerformed

    private void signOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOut1ActionPerformed
        // TODO add your handling code here:
        login l = new login();
        setVisible(false);
        dispose();
        l.setVisible(true);
    }//GEN-LAST:event_signOut1ActionPerformed

    private void signOut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOut2ActionPerformed
        // TODO add your handling code here:
        login l = new login();
        setVisible(false);
        dispose();
        l.setVisible(true);
    }//GEN-LAST:event_signOut2ActionPerformed

    private void signOut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOut3ActionPerformed
        // TODO add your handling code here:
        login l = new login();
        setVisible(false);
        dispose();
        l.setVisible(true);
    }//GEN-LAST:event_signOut3ActionPerformed

    private void searchVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchVehicleButtonActionPerformed
        // TODO add your handling code here:
        String search = searchVehicleText.getText();
        Object[][] row = new Object[3][15];
        Object[][] allVehicleRow = new Object[500][15];

        connection myConnection = new connection();

        try {
            row = myConnection.vehicleSummary(search);
            DefaultTableModel summaryTable = (DefaultTableModel) vehicleSummaryTable.getModel();
            DefaultTableModel allVehicleSummaryTab = (DefaultTableModel) allVehicleSummaryTable.getModel();

            if (!search.isEmpty() && row.length != 0) {
                viewQuotationButton.setVisible(true);
                summaryTable.setNumRows(1);
                summaryTable.setValueAt(row[0][0], 0, 0);
                summaryTable.setValueAt(row[0][1], 0, 1);
                summaryTable.setValueAt(row[0][2], 0, 2);
                summaryTable.setValueAt(row[0][3], 0, 3);
                summaryTable.setValueAt(row[0][4], 0, 4);
                summaryTable.setValueAt(row[0][5], 0, 5);
                summaryTable.setValueAt(row[0][6], 0, 6);
                summaryTable.setValueAt(row[0][7], 0, 7);
            }
            allVehiclesEnrolledLabel.setVisible(true);
            allVehicleSummaryTable.setVisible(true);
            allVehicleRow = myConnection.allVehicleSummary();
            for (i = 0; i < myConnection.totalVehicles; i++) {
                allVehicleSummaryTab.setRowCount(i + 1);
                for (int j = 0; j < 4; j++) {
                    allVehicleSummaryTab.setValueAt(allVehicleRow[i][j], i, j);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(Service_log.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchVehicleButtonActionPerformed

    private void searchVehicleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchVehicleTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchVehicleTextActionPerformed

    private void searchVehicleTextPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_searchVehicleTextPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_searchVehicleTextPropertyChange

    private void viewQuotationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewQuotationButtonActionPerformed
        // TODO add your handling code here:        
        customerView forQuotation = new customerView();
        forQuotation.setVisible(true);
    }//GEN-LAST:event_viewQuotationButtonActionPerformed

    private void deleteBikeModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBikeModelActionPerformed

        // TODO add your handling code here:
        deleteRecords d = new deleteRecords();
        d.setVisible(true);
    }//GEN-LAST:event_deleteBikeModelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Service_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Service_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Service_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Service_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Service_log().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddVehicleButton;
    private javax.swing.JLabel addedLabel;
    private javax.swing.JTable allVehicleSummaryTable;
    private javax.swing.JLabel allVehiclesEnrolledLabel;
    private javax.swing.JButton deleteBikeModel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel orderPlacedLabel;
    private javax.swing.JButton placeOrderButton;
    private javax.swing.JTable qTable;
    private javax.swing.JTable rsTable;
    private javax.swing.JButton searchVehicleButton;
    private javax.swing.JTextField searchVehicleText;
    private javax.swing.JPanel serviceLogPanel;
    private javax.swing.JButton signOut;
    private javax.swing.JButton signOut1;
    private javax.swing.JButton signOut2;
    private javax.swing.JButton signOut3;
    private javax.swing.JButton updateQuotationButton;
    private javax.swing.JLabel updateQuotationLabel;
    private javax.swing.JTabbedPane vehicleDeliveryTab;
    private javax.swing.JTable vehicleSummaryTable;
    private javax.swing.JButton viewQuotationButton;
    private javax.swing.JTable vmTable;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
